/** @type {import('tailwindcss').Config} */
module.exports = {
  // NOTE: Update this to include the paths to all files that contain Nativewind classes.
  content: ["./app/**/*.{js,jsx,ts,tsx}", "./components/**/*.{js,jsx,ts,tsx}", "./context/**/*.{js,jsx,ts,tsx}", "./services/**/*.{js,jsx,ts,tsx}", "./types/**/*.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        primary: "rgb(var(--color-primary) / <alpha-value>)",
        primaryContainer: "rgb(var(--color-primaryContainer) / <alpha-value>)",
        onPrimary: "rgb(var(--color-onPrimary) / <alpha-value>)",
        onPrimaryContainer: "rgb(var(--color-onPrimaryContainer) / <alpha-value>)",
        secondary: "rgb(var(--color-secondary) / <alpha-value>)",
        secondaryContainer: "rgb(var(--color-secondaryContainer) / <alpha-value>)",
        onSecondary: "rgb(var(--color-onSecondary) / <alpha-value>)",
        onSecondaryContainer: "rgb(var(--color-onSecondaryContainer) / <alpha-value>)",
        tertiary: "rgb(var(--color-tertiary) / <alpha-value>)",
        tertiaryContainer: "rgb(var(--color-tertiaryContainer) / <alpha-value>)",
        onTertiary: "rgb(var(--color-onTertiary) / <alpha-value>)",
        onTertiaryContainer: "rgb(var(--color-onTertiaryContainer) / <alpha-value>)",
        error: "rgb(var(--color-error) / <alpha-value>)",
        onError: "rgb(var(--color-onError) / <alpha-value>)",
        errorContainer: "rgb(var(--color-errorContainer) / <alpha-value>)",
        onErrorContainer: "rgb(var(--color-onErrorContainer) / <alpha-value>)",
        background: "rgb(var(--color-background) / <alpha-value>)",
        onBackground: "rgb(var(--color-onBackground) / <alpha-value>)",
        surface: "rgb(var(--color-surface) / <alpha-value>)",
        onSurface: "rgb(var(--color-onSurface) / <alpha-value>)",
        surfaceVariant: "rgb(var(--color-surfaceVariant) / <alpha-value>)",
        onSurfaceVariant: "rgb(var(--color-onSurfaceVariant) / <alpha-value>)",
        outline: "rgb(var(--color-outline) / <alpha-value>)",
        outlineVariant: "rgb(var(--color-outlineVariant) / <alpha-value>)",
        elevationLevel0: "rgb(var(--color-elevation-level0) / <alpha-value>)",
        elevationLevel1: "rgb(var(--color-elevation-level1) / <alpha-value>)",
        elevationLevel2: "rgb(var(--color-elevation-level2) / <alpha-value>)",
        elevationLevel3: "rgb(var(--color-elevation-level3) / <alpha-value>)",
        elevationLevel4: "rgb(var(--color-elevation-level4) / <alpha-value>)",
        elevationLevel5: "rgb(var(--color-elevation-level5) / <alpha-value>)",
        inverseOnSurface: "rgb(var(--color-inverseOnSurface) / <alpha-value>)",
        inverseSurface: "rgb(var(--color-inverseSurface) / <alpha-value>)",
      }
    },
  },
  plugins: [
    ({ addBase }) =>
      addBase({
        ":root": {
        '--color-primary': '0 0 0',
        '--color-primaryContainer': '233 239 254',
        '--color-onPrimary': '255 255 255',
        '--color-onPrimaryContainer': '46 59 157',
        '--color-secondary': '213 78 125',
        '--color-secondaryContainer': '248 221 232',
        '--color-onSecondary': '255 255 255',
        '--color-onSecondaryContainer': '125 27 64',
        '--color-tertiary': '124 91 166',
        '--color-tertiaryContainer': '240 232 255',
        '--color-onTertiary': '255 255 255',
        '--color-onTertiaryContainer': '66 39 94',
        '--color-error': '196 30 58',
        '--color-onError': '255 255 255',
        '--color-errorContainer': '247 216 220',
        '--color-onErrorContainer': '99 10 15',
        '--color-background': '250 251 252',
        '--color-onBackground': '26 32 44',
        '--color-surface': '255 255 255',
        '--color-onSurface': '26 32 44',
        '--color-surfaceVariant': '241 243 251',
        '--color-onSurfaceVariant': '90 95 115',
        '--color-outline': '196 199 208',
        '--color-outlineVariant': '226 228 234',
        '--color-elevation-level0': '0 0 0', // transparent handled via alpha
        '--color-elevation-level1': '247 249 254',
        '--color-elevation-level2': '239 243 253',
        '--color-elevation-level3': '232 236 252',
        '--color-elevation-level4': '229 234 252',
        '--color-elevation-level5': '225 231 250',
        '--color-inverseOnSurface': '242 244 249',
        '--color-inverseSurface': '26 32 44',
        },
      }),
  ],
}